Repository MyCryptoHQ/MyCrypto, pull requests merged in 2018-12, with the labels that each got.

#2187 [FEATURE] Estimate gas used for scheduling.
  common/components/TXMetaDataPanel/components/AdvancedGas.tsx
  common/components/TXMetaDataPanel/components/FeeSummary.tsx
  common/features/schedule/actions.ts
  common/features/schedule/sagas.ts
  common/features/schedule/types.ts
  common/features/selectors.ts
  common/features/transaction/network/sagas.spec.ts
  common/features/transaction/network/sagas.ts
  common/features/transaction/sagas.spec.ts
  common/features/transaction/sagas.ts
  common/libs/scheduling/index.ts
Labels: Oct 28th

#2228 [SCHEDULING] Move advanced scheduling options to +Advanced section
  common/components/TXMetaDataPanel/components/AdvancedGas.tsx
  common/containers/Tabs/ScheduleTransaction/components/Fields/TimeBounty/TimeBountyField.scss
  common/containers/Tabs/ScheduleTransaction/components/Fields/TimeBounty/TimeBountyField.tsx
  common/containers/Tabs/ScheduleTransaction/components/ScheduleFields.tsx
Labels: Nov 8th

#2206 Add support for iOlite Network
  common/config/dpaths.ts
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  shared/types/network.d.ts
Labels: Oct 28th

#2306 Remove read-only attribute from symbol and decimal input
  common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/DecimalField.tsx
  common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/SymbolField.tsx
Labels: 2018-12-20

#2309 Update icn-bank-vs-mycrypto.svg
  common/assets/images/icn-bank-vs-mycrypto.svg
Labels: 2018-12-20

#2310 Update icn-trezor-new.svg
  common/assets/images/icn-trezor-new.svg
Labels: 2018-12-20

#2315 Add hardware wallet support for REOSC Ecosystem
  common/config/dpaths.ts
  common/features/config/__snapshots__/sagas.spec.ts.snap
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  shared/types/network.d.ts
Labels: 2018-12-20

#2318 Change "MetaMask / Mist" -> "MetaMask / Web3"
  common/containers/Tabs/SendTransaction/components/UnavailableWallets.tsx
  common/features/config/sagas.ts
  common/features/configAndTokens.ts
  common/features/wallet/sagas.spec.ts
  common/libs/nodes/web3/index.ts
  common/libs/wallet/non-deterministic/web3.ts
  common/translations/lang/ar.json
  common/translations/lang/de.json
  common/translations/lang/el.json
  common/translations/lang/es.json
  common/translations/lang/fi.json
  common/translations/lang/fr.json
  common/translations/lang/ht.json
  common/translations/lang/hu.json
  common/translations/lang/id.json
  common/translations/lang/it.json
  common/translations/lang/ja.json
  common/translations/lang/nl.json
  common/translations/lang/no.json
  common/translations/lang/pl.json
  common/translations/lang/pt.json
  common/translations/lang/ru.json
  common/translations/lang/sk.json
  common/translations/lang/sl.json
  common/translations/lang/sv.json
  common/translations/lang/tr.json
  common/translations/lang/vi.json
  common/translations/lang/zhcn.json
  common/translations/lang/zhtw.json
Labels: 2018-12-20

#2319 Add a description to the "View Address" option in WalletDecrypt
  common/components/WalletDecrypt/WalletDecrypt.tsx
  common/translations/lang/ar.json
  common/translations/lang/de.json
  common/translations/lang/el.json
  common/translations/lang/en.json
  common/translations/lang/es.json
  common/translations/lang/fi.json
  common/translations/lang/fr.json
  common/translations/lang/ht.json
  common/translations/lang/hu.json
  common/translations/lang/id.json
  common/translations/lang/it.json
  common/translations/lang/ja.json
  common/translations/lang/ko.json
  common/translations/lang/nl.json
  common/translations/lang/no.json
  common/translations/lang/pl.json
  common/translations/lang/pt.json
  common/translations/lang/ru.json
  common/translations/lang/sk.json
  common/translations/lang/sl.json
  common/translations/lang/sv.json
  common/translations/lang/tr.json
  common/translations/lang/vi.json
  common/translations/lang/zhcn.json
  common/translations/lang/zhtw.json
Labels: 2018-12-20

#2320 [BUGFIX] Do not switch off scheduling toggle when token has been selected
  common/features/transaction/meta/sagas.spec.ts
  common/features/transaction/meta/sagas.ts
Labels: 2018-12-20

#2324 [BUGFIX] Fix disabled Schedule button
  common/containers/Tabs/ScheduleTransaction/components/Fields/WindowSize/WindowSizeFieldFactory/WindowSizeFieldFactory.tsx
  common/containers/Tabs/ScheduleTransaction/components/Fields/WindowSize/WindowSizeFieldFactory/WindowSizeInputFactory.tsx
  common/containers/Tabs/ScheduleTransaction/components/Fields/WindowSize/WindowSizeFieldFactory/index.ts
  common/containers/Tabs/ScheduleTransaction/components/Fields/WindowSizeField.tsx
  common/containers/Tabs/ScheduleTransaction/components/index.ts
  common/features/schedule/reducer.ts
  common/features/schedule/sagas.ts
Labels: 2018-12-20

#2325 [MERGE BEFORE 1/1] Change instances of 2018 to 2019
  LICENSE
  common/components/DisclaimerModal.tsx
Labels: 2018-12-20

#2312 Add nonce auto-update on transaction send
  common/features/transaction/network/sagas.spec.ts
  common/features/transaction/network/sagas.ts
  common/features/transaction/sagas.ts
  common/features/transactions/sagas.ts
  common/utils/formatters.ts
  shared/types/transactions.d.ts
Labels: 2019-01-10
