Repository MyCryptoHQ/MyCrypto, pull requests merged in 2018-05, with the labels that each got.

#1698 Fix Estimate Gas
  common/libs/nodes/rpc/utils.ts
  common/sagas/transaction/network/gas.ts
Labels: RC

#1708 Fix retry scan if you have no tokens
  common/sagas/wallet/wallet.ts
Labels: RC

#1697 Remove checksumming of keystore address
  common/libs/web-workers/workers/generateKeystore.worker.ts
Labels: RC

#1655 Japanese V4 full translation
  common/translations/lang/ja.json
Labels: RC

#1714 [FEATURE] Upgrade EAC libs to v1.0.0-beta.3.
  common/libs/scheduling/contracts/RequestFactory.ts
  common/libs/scheduling/index.ts
  common/selectors/schedule/transaction.ts
Labels: RC

#1673 Production Release Changes
  README.md
  common/Root.tsx
  common/components/BetaAgreement/index.scss
  common/components/BetaAgreement/index.tsx
  common/components/Footer/index.tsx
  common/components/Header/components/OnlineStatus.scss
  common/components/Header/components/OnlineStatus.tsx
  common/components/WelcomeModal.scss
  common/components/WelcomeModal.tsx
  common/components/index.ts
  common/components/ui/Modal/ModalBody.tsx
  common/components/ui/Modal/index.scss
  common/components/ui/Modal/index.tsx
  common/components/ui/TitleBar.scss
  common/components/ui/TitleBar.tsx
  common/components/ui/Tooltip.scss
  common/components/ui/Tooltip.tsx
  common/components/ui/index.ts
  common/config/data.tsx
  common/config/links.ts
  common/containers/OnboardModal/index.tsx
  common/containers/TabSection/WebTemplate.tsx
  common/sass/mixins.scss
  common/sass/variables.scss
  common/sass/variables/tooltips.scss
  common/translations/lang/en.json
  common/utils/formatters.ts
  common/utils/localStorage.ts
Labels: RC, ready for review

#1736 Increase shepherd thresholds
  common/libs/nodes/index.ts
  package.json
  yarn.lock
Labels: RC

#1731 Parse bytes types to a hex buffer
  common/libs/contracts/ABIFunction.ts
Labels: RC

#1660 Node Refactor (Pt. 4 - Electron Network Selector)
  common/components/ElectronNav/ElectronNav.tsx
  common/components/ElectronNav/NetworkSelect.tsx
  common/components/ElectronNav/NodeSelect.scss
  common/components/ElectronNav/NodeSelect.tsx
  common/components/Header/components/NetworkDropdown.scss
  common/components/Header/components/NetworkDropdown.tsx
  common/components/Header/index.tsx
  common/components/NetworkSelector/NetworkOption.scss
  common/components/NetworkSelector/NetworkOption.tsx
  common/components/NetworkSelector/NetworkSelector.scss
  common/components/NetworkSelector/NetworkSelector.tsx
  common/components/NetworkSelector/NodeOption.scss
  common/components/NetworkSelector/NodeOption.tsx
  common/components/NetworkSelector/index.tsx
  common/sagas/config/node.ts
  common/selectors/config/nodes.ts
  common/translations/lang/en.json
  shared/types/node.d.ts
Labels: ready for review

#1654 Node Refactor (Pt. 3 - Node & Network Cleanup)
  common/actions/config/actionTypes.ts
  common/components/BalanceSidebar/AccountInfo.tsx
  common/components/CustomNodeModal/CustomNodeModal.tsx
  common/components/ElectronNav/ElectronNav.tsx
  common/components/ElectronNav/NetworkSelect.tsx
  common/components/ElectronNav/NodeSelect.scss
  common/components/ElectronNav/NodeSelect.tsx
  common/components/Header/components/NetworkDropdown.scss
  common/components/Header/components/NetworkDropdown.tsx
  common/components/Header/index.tsx
  common/components/NetworkSelector/NetworkOption.scss
  common/components/NetworkSelector/NetworkOption.tsx
  common/components/NetworkSelector/NetworkSelector.scss
  common/components/NetworkSelector/NetworkSelector.tsx
  common/components/NetworkSelector/NodeOption.scss
  common/components/NetworkSelector/NodeOption.tsx
  common/components/NetworkSelector/index.tsx
  common/containers/Tabs/CheckTransaction/index.tsx
  common/libs/nodes/web3/index.ts
  common/libs/wallet/non-deterministic/web3.ts
  common/reducers/config/networks/customNetworks.ts
  common/reducers/config/networks/staticNetworks.ts
  common/reducers/config/nodes/customNodes.ts
  common/sagas/config/network.ts
  common/sagas/config/node.ts
  common/sagas/config/web3.ts
  common/selectors/config/networks.ts
  common/selectors/config/nodes.ts
  common/translations/lang/en.json
  shared/types/network.d.ts
  shared/types/node.d.ts
  spec/reducers/config/config.spec.ts
  spec/reducers/config/networks/customNetworks.spec.ts
  spec/reducers/config/nodes/customNodes.spec.ts
  spec/sagas/config/node.spec.ts
  spec/sagas/gas.spec.ts
Labels: ready for review

#1640 Node Refactor (Pt. 2 - Web Node Selector Rework)
  common/actions/config/actionCreators.ts
  common/actions/config/actionTypes.ts
  common/actions/config/constants.ts
  common/components/BalanceSidebar/AccountInfo.tsx
  common/components/CustomNodeModal/CustomNodeModal.tsx
  common/components/ElectronNav/ElectronNav.tsx
  common/components/ElectronNav/NetworkSelect.tsx
  common/components/ElectronNav/NodeSelect.scss
  common/components/ElectronNav/NodeSelect.tsx
  common/components/Header/components/NetworkDropdown.scss
  common/components/Header/components/NetworkDropdown.tsx
  common/components/Header/index.tsx
  common/components/NetworkSelector/NetworkOption.scss
  common/components/NetworkSelector/NetworkOption.tsx
  common/components/NetworkSelector/NetworkSelector.scss
  common/components/NetworkSelector/NetworkSelector.tsx
  common/components/NetworkSelector/NodeOption.scss
  common/components/NetworkSelector/NodeOption.tsx
  common/components/NetworkSelector/index.tsx
  common/components/ui/ColorDropdown.scss
  common/components/ui/ColorDropdown.tsx
  common/components/ui/DropdownShell.tsx
  common/components/ui/index.ts
  common/containers/TabSection/WebTemplate.tsx
  common/containers/Tabs/CheckTransaction/index.tsx
  common/libs/nodes/configs.ts
  common/libs/nodes/index.ts
  common/libs/nodes/web3/index.ts
  common/libs/wallet/non-deterministic/web3.ts
  common/reducers/config/networks/customNetworks.ts
  common/reducers/config/networks/staticNetworks.ts
  common/reducers/config/nodes/customNodes.ts
  common/reducers/config/nodes/selectedNode.ts
  common/reducers/config/nodes/staticNodes.ts
  common/sagas/config/network.ts
  common/sagas/config/node.ts
  common/sagas/config/web3.ts
  common/sagas/transactions.ts
  common/sass/styles/overrides/dropdowns.scss
  common/sass/variables.scss
  common/selectors/config/networks.ts
  common/selectors/config/nodes.ts
  common/translations/lang/en.json
  shared/types/network.d.ts
  shared/types/node.d.ts
  spec/reducers/config/__snapshots__/config.spec.ts.snap
  spec/reducers/config/config.spec.ts
  spec/reducers/config/networks/customNetworks.spec.ts
  spec/reducers/config/nodes/customNodes.spec.ts
  spec/reducers/config/nodes/selectedNode.spec.ts
  spec/reducers/config/nodes/staticNodes.spec.ts
  spec/sagas/config/node.spec.ts
  spec/sagas/gas.spec.ts
  spec/sagas/wallet.spec.tsx
Labels: ready for review

#1603 Node Refactor
  common/actions/config/actionCreators.ts
  common/actions/config/actionTypes.ts
  common/actions/config/constants.ts
  common/components/BalanceSidebar/AccountInfo.tsx
  common/components/CustomNodeModal/CustomNodeModal.tsx
  common/components/ElectronNav/ElectronNav.tsx
  common/components/ElectronNav/NetworkSelect.tsx
  common/components/ElectronNav/NodeSelect.scss
  common/components/ElectronNav/NodeSelect.tsx
  common/components/Header/components/NetworkDropdown.scss
  common/components/Header/components/NetworkDropdown.tsx
  common/components/Header/index.tsx
  common/components/NetworkSelector/NetworkOption.scss
  common/components/NetworkSelector/NetworkOption.tsx
  common/components/NetworkSelector/NetworkSelector.scss
  common/components/NetworkSelector/NetworkSelector.tsx
  common/components/NetworkSelector/NodeOption.scss
  common/components/NetworkSelector/NodeOption.tsx
  common/components/NetworkSelector/index.tsx
  common/components/ui/ColorDropdown.scss
  common/components/ui/ColorDropdown.tsx
  common/components/ui/DropdownShell.tsx
  common/components/ui/index.ts
  common/containers/TabSection/WebTemplate.tsx
  common/containers/Tabs/CheckTransaction/index.tsx
  common/libs/nodes/configs.ts
  common/libs/nodes/index.ts
  common/libs/nodes/web3/index.ts
  common/libs/wallet/non-deterministic/web3.ts
  common/reducers/config/networks/customNetworks.ts
  common/reducers/config/networks/staticNetworks.ts
  common/reducers/config/nodes/customNodes.ts
  common/reducers/config/nodes/selectedNode.ts
  common/reducers/config/nodes/staticNodes.ts
  common/sagas/config/network.ts
  common/sagas/config/node.ts
  common/sagas/config/web3.ts
  common/sagas/transactions.ts
  common/sass/styles/overrides/dropdowns.scss
  common/sass/variables.scss
  common/selectors/config/networks.ts
  common/selectors/config/nodes.ts
  common/store/configAndTokens.ts
  common/translations/lang/en.json
  shared/types/network.d.ts
  shared/types/node.d.ts
  spec/integration/data.int.ts
  spec/reducers/config/__snapshots__/config.spec.ts.snap
  spec/reducers/config/config.spec.ts
  spec/reducers/config/networks/customNetworks.spec.ts
  spec/reducers/config/nodes/customNodes.spec.ts
  spec/reducers/config/nodes/selectedNode.spec.ts
  spec/reducers/config/nodes/staticNodes.spec.ts
  spec/sagas/config/node.spec.ts
  spec/sagas/gas.spec.ts
  spec/sagas/wallet.spec.tsx
Labels: ready for review

#1862 Add New Networks w/ Refactor (MUSIC, ETSC, EGEM, CLO)
  common/config/dpaths.ts
  common/libs/nodes/configs.ts
  common/reducers/config/networks/staticNetworks.ts
  shared/types/network.d.ts
  shared/types/node.d.ts
Labels: ready for review
