Repository MyCryptoHQ/MyCrypto, pull requests merged in 2018-04, with the labels that each got.

#1428 Add checksumming to payment request & confirmation modal
  common/components/AddressField.tsx
  common/components/ConfirmationModal/components/Body/components/Addresses.tsx
  common/containers/Tabs/SendTransaction/components/RequestPayment.tsx
Labels: ready for review

#1447 Harden Jenkins Pipelines
  jenkins/Jenkinsfile.darwin
  jenkins/Jenkinsfile.linux.develop
  jenkins/Jenkinsfile.linux.master
Labels: build / ci, ready for review

#1429 Fix gastracker url path
  common/reducers/config/networks/staticNetworks.ts
Labels: ready for review

#1459 Add coverage reporting with coveralls
  .travis.yml
  jest_config/jest.config.json
  jest_config/jest.int.config.json
  package.json
Labels: build / ci, ready for review

#1458 Fix editor config
  .editorconfig
Labels: ready for review

#1259 Add New Networks
  common/components/WalletDecrypt/components/LedgerNano.tsx
  common/components/WalletDecrypt/components/Mnemonic.tsx
  common/components/WalletDecrypt/components/Trezor.tsx
  common/components/WalletDecrypt/components/UnsupportedNetwork.tsx
  common/config/dpaths.ts
  common/reducers/config/networks/staticNetworks.ts
  common/reducers/config/nodes/staticNodes.ts
  common/selectors/config/wallet.ts
  common/selectors/wallet.ts
  shared/types/network.d.ts
  shared/types/node.d.ts
  spec/reducers/config/__snapshots__/config.spec.ts.snap
  spec/reducers/config/nodes/staticNodes.spec.ts
Labels: help wanted, ready for review

#1463 Reduce Shapeshift Requests
  common/api/shapeshift.ts
  common/containers/Tabs/Swap/components/CurrencySwap.scss
  common/containers/Tabs/Swap/components/CurrencySwap.tsx
  common/containers/Tabs/Swap/components/CurrentRates.scss
  common/containers/Tabs/Swap/components/CurrentRates.tsx
Labels: ready for review

#1465 Fix keystore worker in dev
  webpack_config/makeConfig.js
Labels: ready for review

#1413 Shepherd MVP Integration
  common/actions/config/actionTypes.ts
  common/components/Header/components/CustomNodeModal.tsx
  common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
  common/libs/nodes/custom/index.ts
  common/libs/nodes/etherscan/client.ts
  common/libs/nodes/etherscan/index.ts
  common/libs/nodes/etherscan/requests.ts
  common/libs/nodes/etherscan/types.ts
  common/libs/nodes/index.ts
  common/libs/nodes/infura/client.ts
  common/libs/nodes/infura/index.ts
  common/libs/nodes/tokenBalanceProxy.ts
  common/libs/wallet/non-deterministic/web3.ts
  common/reducers/config/nodes/selectedNode.ts
  common/reducers/config/nodes/staticNodes.ts
  common/reducers/config/nodes/types.ts
  common/sagas/config/node.ts
  common/sagas/config/web3.ts
  common/sagas/wallet/wallet.ts
  common/selectors/config/networks.ts
  common/selectors/config/nodes.ts
  common/store/configAndTokens.ts
  package.json
  shared/types/node.d.ts
  spec/integration/RpcNodeTestConfig.js
  spec/integration/data.int.ts
  spec/reducers/config/__snapshots__/config.spec.ts.snap
  spec/reducers/config/config.spec.ts
  spec/reducers/config/nodes/selectedNode.spec.ts
  spec/reducers/config/nodes/staticNodes.spec.ts
  spec/sagas/__snapshots__/wallet.spec.tsx.snap
  spec/sagas/wallet.spec.tsx
  tsconfig.json
Labels: ready for review

#1462 Add Etherchain links
  common/components/BalanceSidebar/AccountInfo.tsx
  common/components/ExtendedNotifications/TransactionSucceeded.tsx
  common/components/Footer/index.tsx
  common/config/data.tsx
  common/containers/Tabs/CheckTransaction/index.tsx
  common/reducers/config/networks/staticNetworks.ts
  common/translations/lang/en.json
  common/utils/helpers.ts
Labels: ready for review

#1473 Fix sign message not returning back to caller
  common/libs/wallet/deterministic/ledger.ts
Labels: ready for review

#1486 Add Jenkins CI
  jenkins/Jenkinsfile.darwin.ci
  webpack_config/buildElectron.js
Labels: build / ci, ready for review

#1500 Downgrade rc-slider to fix alignment issues
  package.json
Labels: ready for review

#1496 Allow network selection via query parameter
  common/actions/config/actionCreators.ts
  common/actions/config/actionTypes.ts
  common/actions/config/constants.ts
  common/components/Header/index.tsx
  common/components/renderCbs/Query.tsx
  common/containers/TabSection/index.tsx
  common/sagas/config/node.ts
  spec/reducers/config/config.spec.ts
Labels: ready for review

#1509 Fix Parity QR Signer on Non Send Pages
  common/Root.tsx
  common/containers/Tabs/SendTransaction/index.tsx
Labels: ready for review

#1506 Fix misc links and translations
  common/components/Footer/index.tsx
  common/components/Header/components/CustomNodeModal.tsx
  common/components/Translate.tsx
  common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
  common/components/WalletDecrypt/components/LedgerNano.tsx
  common/components/WalletDecrypt/components/Mnemonic.tsx
  common/components/WalletDecrypt/components/Trezor.tsx
  common/translations/lang/en.json
Labels: ready for review

#1512 Use Yarn in Jenkins Electron Builds
  jenkins/Jenkinsfile.darwin
  jenkins/Jenkinsfile.darwin.ci
  jenkins/Jenkinsfile.linux.develop
  jenkins/Jenkinsfile.linux.master
Labels: build / ci, ready for review

#1247 Create script to update tokens list from ethereum-lists/tokens
  package.json
  scripts/types/CommitStatus.ts
  scripts/types/GitCommit.ts
  scripts/types/TokensJson.ts
  scripts/update-tokens-utils.ts
  scripts/update-tokens.ts
  tsconfig.json
Labels: discussion, ready for review

#1498 Update ETH Token List
  common/config/tokens/eth.json
  spec/config/tokens.spec.ts
Labels: ready for review

#1514 Show Recent Addresses on View Only
  common/components/WalletDecrypt/components/Keystore.tsx
  common/components/WalletDecrypt/components/ViewOnly.scss
  common/components/WalletDecrypt/components/ViewOnly.tsx
  common/components/ui/Input.scss
  common/reducers/wallet.ts
  common/sass/styles/overrides/react-select.scss
  common/sass/variables/forms.scss
  common/selectors/wallet.ts
  common/store/store.ts
  common/translations/lang/en.json
  spec/reducers/wallet.spec.ts
Labels: ready for review

#1518 Add Ethereum Commonwealth ETC node
  common/libs/nodes/index.ts
  common/reducers/config/nodes/staticNodes.ts
  shared/types/node.d.ts
Labels: ready for review

#1526 Deprecation Warning for Insecure Unlocks
  common/components/WalletDecrypt/components/DeprecationWarning.tsx
  common/components/WalletDecrypt/components/Keystore.tsx
  common/components/WalletDecrypt/components/Mnemonic.tsx
  common/components/WalletDecrypt/components/PrivateKey.tsx
  common/sass/styles/scaffolding.scss
  common/translations/lang/en.json
Labels: ready for review

#1519 Fix TREZOR dpath on TOMO network
  common/reducers/config/networks/staticNetworks.ts
Labels: ready for review

#1517 Fix Ledger DPaths, Improve Error Messaging
  common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
  common/components/WalletDecrypt/components/LedgerNano.tsx
  common/config/dpaths.ts
  common/libs/validators.ts
  common/reducers/config/networks/staticNetworks.ts
  common/sass/styles/overrides/alerts.scss
  common/translations/lang/en.json
Labels: ready for review

#1505 Electron Redesign
  common/Root.tsx
  common/assets/images/logo-ethercards.png
  common/assets/images/logo-mycrypto-transparent.svg
  common/components/CustomNodeModal/CustomNodeModal.scss
  common/components/CustomNodeModal/CustomNodeModal.tsx
  common/components/CustomNodeModal/index.ts
  common/components/DisclaimerModal.scss
  common/components/DisclaimerModal.tsx
  common/components/ElectronNav/ElectronNav.scss
  common/components/ElectronNav/ElectronNav.tsx
  common/components/ElectronNav/LanguageSelect.scss
  common/components/ElectronNav/LanguageSelect.tsx
  common/components/ElectronNav/NetworkStatus.scss
  common/components/ElectronNav/NetworkStatus.tsx
  common/components/ElectronNav/NodeSelect.scss
  common/components/ElectronNav/NodeSelect.tsx
  common/components/ElectronNav/index.tsx
  common/components/Footer/index.tsx
  common/components/Header/components/Navigation.scss
  common/components/Header/components/Navigation.tsx
  common/components/Header/components/NavigationLink.scss
  common/components/Header/index.tsx
  common/components/NavigationLink.tsx
  common/components/SubTabs/SubTabs.scss
  common/components/WalletDecrypt/WalletDecrypt.scss
  common/components/index.ts
  common/components/ui/Modal/index.tsx
  common/components/ui/NewTabLink.tsx
  common/config/data.tsx
  common/config/index.ts
  common/config/links.ts
  common/config/navigation.ts
  common/containers/OnboardModal/index.scss
  common/containers/OnboardModal/index.tsx
  common/containers/TabSection/ElectronTemplate.scss
  common/containers/TabSection/ElectronTemplate.tsx
  common/containers/TabSection/WebTemplate.scss
  common/containers/TabSection/WebTemplate.tsx
  common/containers/TabSection/index.tsx
  common/containers/Tabs/SupportPage/index.scss
  common/containers/Tabs/SupportPage/index.tsx
  common/sass/styles/scaffolding.scss
  common/sass/variables.scss
  common/sass/variables/electron.scss
  common/sass/variables/grid.scss
  common/selectors/config/nodes.ts
  common/translations/lang/en.json
  electron-app/main/window.ts
  package.json
  spec/pages/__snapshots__/ENS.spec.tsx.snap
  webpack_config/makeConfig.js
Labels: ready for review

#1652 Node Refactor (Pt. 2.5 - Action Nomenclature)
  common/actions/config/actionCreators.ts
  common/actions/config/actionTypes.ts
  common/actions/config/constants.ts
  common/components/ElectronNav/NodeSelect.tsx
  common/components/Header/components/NetworkSelector/NetworkSelector.tsx
  common/components/Header/index.tsx
  common/reducers/config/nodes/selectedNode.ts
  common/sagas/config/node.ts
  common/sagas/config/web3.ts
  common/sagas/transactions.ts
  spec/reducers/config/__snapshots__/config.spec.ts.snap
  spec/reducers/config/config.spec.ts
  spec/reducers/config/nodes/selectedNode.spec.ts
  spec/sagas/config/node.spec.ts
  spec/sagas/wallet.spec.tsx
Labels: ready for review

#1661 Update Create Wallet Tutorial Screenshots
  common/assets/images/unlock-guide/open-app.png
  common/assets/images/unlock-guide/open-web.png
  common/assets/images/unlock-guide/tab-app.png
  common/assets/images/unlock-guide/tab-web.png
  common/containers/Tabs/GenerateWallet/components/FinalSteps.tsx
  common/translations/lang/en.json
Labels: ready for review

#1664 Add Jenkins Config for Mac Signing
  jenkins/Jenkinsfile.darwin.signing
Labels: build / ci

#1665 Electron Alpha Prep
  common/Root.tsx
  common/components/AppAlphaNotice/AlphaNotice.scss
  common/components/AppAlphaNotice/AlphaNotice.tsx
  common/components/AppAlphaNotice/AppExpired.scss
  common/components/AppAlphaNotice/AppExpired.tsx
  common/components/AppAlphaNotice/index.tsx
  common/components/ElectronNav/ElectronNav.tsx
  common/components/NewAppReleaseModal.tsx
  common/components/index.ts
  common/config/data.tsx
  common/containers/TabSection/ElectronTemplate.tsx
  common/translations/lang/en.json
  common/utils/helpers.ts
  electron-app/main/window.ts
  package.json
  spec/utils/helpers.spec.ts
Labels: ready for review

#1663 Enable Parity Signer Message Signing
  common/actions/message/actionCreators.ts
  common/actions/message/actionTypes.ts
  common/actions/message/constants.ts
  common/actions/message/index.ts
  common/actions/paritySigner/actionCreators.ts
  common/actions/paritySigner/actionTypes.ts
  common/actions/paritySigner/constants.ts
  common/components/ParityQrSigner.tsx
  common/components/WalletDecrypt/disables.ts
  common/containers/QrSignerModal/index.tsx
  common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/SignButton.tsx
  common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/index.tsx
  common/containers/Tabs/SignAndVerifyMessage/components/VerifyMessage/index.tsx
  common/libs/wallet/non-deterministic/parity.ts
  common/reducers/index.ts
  common/reducers/message.ts
  common/reducers/paritySigner.ts
  common/sagas/index.ts
  common/sagas/message/helpers.ts
  common/sagas/message/index.ts
  common/sagas/message/signing.ts
  common/sagas/transaction/signing/signing.ts
  common/translations/lang/en.json
  package.json
Labels: ready for review

#1695 Trezor Help Link & Decrypt UI
  common/components/WalletDecrypt/WalletDecrypt.scss
  common/components/WalletDecrypt/WalletDecrypt.tsx
  common/components/WalletDecrypt/components/Trezor.tsx
Labels: ready for review
