Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-05, with the labels that each got.

#2529 redirect user from dashboard if no account exists
  common/translations/lang/en.json
  common/v2/features/Dashboard/components/AccountList.tsx
Labels: status: ready to merge, type: GAU

#2534 Select Network
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/AddAccount/AddAccountStyles.scss
Labels: status: approved by qa, status: ready to merge, type: GAU

#2538 enable web3 on add-existing-account flow
  common/v2/features/AddAccount/AddAccount.tsx
Labels: type: GAU

#2542 Fix incorrect URL for non-auctioned ENS domains
  common/containers/Tabs/ENS/components/NameResolve/components/NameAuction.tsx
  common/containers/Tabs/ENS/components/NameResolve/components/NameForbidden.tsx
  common/containers/Tabs/ENS/components/NameResolve/components/NameNotYetAvailable.tsx
  common/containers/Tabs/ENS/components/NameResolve/components/NameOpen.tsx
  common/translations/lang/en.json
Labels: cat: ens, status: ready for qa, type: issue

#2530 CW-32/account dropdown
  common/Root.tsx
  common/translations/lang/en.json
  common/v2/components/Checkbox.tsx
  common/v2/components/index.ts
  common/v2/features/Dashboard/components/AccountDropdown.scss
  common/v2/features/Dashboard/components/AccountDropdown.tsx
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
  common/v2/providers/CurrentsProvider/CurrentsProvider.tsx
  common/v2/services/Currents/types.ts
  common/v2/services/Effects/index.ts
  common/v2/services/Effects/useOnClickOutside.tsx
  common/v2/services/LocalCache/constants.ts
  common/v2/services/index.ts
  common/v2/theme/colors.scss
  common/v2/theme/index.js
  common/v2/types/global.d.ts
  package.json
  yarn.lock
Labels: type: GAU

#2543 Add WalletType filtering for networks tab
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/Wallets/types.ts
  common/v2/libs/networks/networks.ts
  common/v2/libs/networks/types.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
  common/v2/services/NetworkOptions/types.ts
Labels: status: ready for qa, type: GAU

#2548 Enable parity signer for Add Account Flow
  common/v2/features/AddAccount/AddAccount.tsx
Labels: status: approved by qa, status: ready to merge, type: GAU

#2557 Fix radio button stretching
  common/v2/features/AddAccount/components/DeterministicWallets.scss
  common/v2/features/AddAccount/components/DeterministicWallets.tsx
Labels: status: ready to merge, type: GAU

#2562 add-existing-account refactor -> onUnlock handling
  common/v2/features/AddAccount/AddAccountFlow.tsx
  common/v2/features/AddAccount/AddAccountForm.reducer.tsx
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/AddAccount/stories.tsx
  common/v2/features/AddAccount/types.tsx
Labels: type: GAU, wip

#2558 Feature/dashboard notifications
  common/Root.tsx
  common/assets/images/icn-don-t-lose-crypto.svg
  common/assets/images/icn-how-do-i-buy-crypto.svg
  common/assets/images/icn-questions.svg
  common/assets/images/icn-save-dash-board-settings.svg
  common/assets/images/icn-wallet.svg
  common/translations/lang/en.json
  common/v2/features/Dashboard/Dashboard.scss
  common/v2/features/Dashboard/Dashboard.tsx
  common/v2/features/Dashboard/NotificationsPanel/NotificationsPanel.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/GetHardwareWalletNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/NotificationWrapper.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/PrintPaperWalletNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/SaveDashboardNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletAddedNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletCreatedNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/index.ts
  common/v2/features/Dashboard/NotificationsPanel/index.ts
  common/v2/features/DevTools/DevTools.tsx
  common/v2/features/DevTools/ToolsNotifications.tsx
  common/v2/providers/ActiveNotificationsProvider/ActiveNotificationsProvider.tsx
  common/v2/providers/ActiveNotificationsProvider/index.ts
  common/v2/providers/NotificationsProvider/NotificationsProvider.tsx
  common/v2/providers/NotificationsProvider/constants.ts
  common/v2/providers/NotificationsProvider/helpers.ts
  common/v2/providers/NotificationsProvider/index.ts
  common/v2/providers/NotificationsProvider/types.ts
  common/v2/providers/index.ts
  common/v2/services/ActiveNotifications/ActiveNotifications.ts
  common/v2/services/ActiveNotifications/index.ts
  common/v2/services/ActiveNotifications/types.ts
  common/v2/services/Analytics/constants.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
  common/v2/services/Notifications/Notifications.ts
  common/v2/services/Notifications/index.ts
  common/v2/services/Notifications/types.ts
  common/v2/services/types.ts
  scripts/update-tokens-utils.ts
  scripts/update-tokens.ts
Labels: type: GAU

#2559 initial setup of sign transaction with wallets flow
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/components/SignTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Mnemonic.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Parity.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/index.ts
  common/v2/features/SendAssets/components/TransactionComplete.tsx
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/index.ts
  common/v2/features/SendAssets/constants.js
  common/v2/features/SendAssets/constants.ts
Labels: status: ready to merge, type: GAU

#2555 Send-assets form fields handler methods
  common/v2/api/bity.ts
  common/v2/api/emails.ts
  common/v2/api/gas.ts
  common/v2/api/index.ts
  common/v2/api/rates.ts
  common/v2/api/utils.ts
  common/v2/features/Gas/gasPriceFunctions.ts
  common/v2/features/Gas/index.ts
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/fields/GasPriceField.tsx
  common/v2/features/SendAssets/components/fields/GasPriceSlider.tsx
  common/v2/features/index.ts
  common/v2/libs/accounts/accounts.ts
  common/v2/libs/accounts/index.ts
  common/v2/libs/networks/networks.ts
Labels: type: GAU, wip

#2572 Fix inconsistent Node version in readme
  README.md
Labels: release: 1.6.7, status: ready to merge

#2569 Add WebUSB support for Ledger devices
  common/components/WalletDecrypt/components/LedgerNano.tsx
  common/libs/wallet/deterministic/ledger.ts
  common/typescript/ledger/hw-transport-webusb.d.ts
  package.json
  yarn.lock
Labels: release: 1.6.7, status: approved by qa, status: ready to merge

#2552 Update rsk.json
  common/config/contracts/rsk.json
Labels: release: 1.6.7, status: approved by qa, status: ready to merge

#2566 Add Crypto10 (Hedged) contract and ABI
  common/config/contracts/eth.json
Labels: release: 1.6.7, status: approved by qa, status: ready to merge

#2565 Fix yarn audit for production/Electron package dependencies
  yarn.lock
Labels: release: 1.6.7, status: approved by qa, status: ready to merge

#2582 Fixed tokens initialization in networkOptions
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
  common/v2/services/NetworkOptions/types.ts
Labels: type: GAU

#2583 Sa/private key styles
  common/v2/components/ContentPanel.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/SignTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.tsx
Labels: type: GAU

#2553 Pre-filled Transaction Implementation for Send-Assets Flow
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/libs/assetOptions.ts
  common/v2/libs/helpers.ts
  common/v2/libs/index.ts
  common/v2/libs/preFillTx/constants.ts
  common/v2/libs/preFillTx/helpers.ts
  common/v2/libs/preFillTx/index.ts
  common/v2/libs/preFillTx/types.ts
  common/v2/libs/transaction/process.ts
Labels: type: GAU, wip

#2589 Menu hover fix
  common/v2/features/Layout/Header/Header.tsx
Labels: type: GAU

#2581 Temporarily fall back to U2F on Windows with Ledger devices
  common/libs/wallet/deterministic/ledger.ts
Labels: status: approved by qa, status: ready to merge

#2588 Account balance fetch
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/Dashboard/components/AccountList.tsx
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/features/Wallets/web3/web3.ts
  common/v2/libs/accounts/accounts.ts
  common/v2/libs/accounts/index.ts
  common/v2/libs/assets/assets.ts
  common/v2/libs/assets/index.ts
  common/v2/libs/index.ts
  common/v2/libs/networks/networks.ts
  common/v2/providers/AccountProvider/AccountProvider.tsx
  common/v2/services/Account/Account.ts
  common/v2/services/Account/types.ts
  common/v2/services/LocalCache/constants.ts
  common/v2/services/NodeOptions/types.ts
Labels: type: GAU

#2602 Added release verification guide to README
  README.md
Labels: status: ready to merge

#2503 Implement basic analytics
  common/Root.tsx
  common/v2/services/Analytics/Analytics.spec.ts
  common/v2/services/Analytics/Analytics.ts
  common/v2/services/Analytics/constants.ts
  common/v2/services/Analytics/index.ts
  common/v2/services/Analytics/types.ts
  common/v2/services/index.ts
Labels: status: ready for review
