Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-02, with the labels that each got.

#2365 Remove ETC Web3 by Gastracker
  common/libs/nodes/configs.ts
Labels: 2019-02-01

#2368 Remove unnecessary `console.log`
  common/components/ui/Input.tsx
  common/utils/versioning/index.ts
Labels: 2019-02-01

#2369 update infura enpoints to v3 api
  common/libs/nodes/configs.ts
Labels: 2019-02-01

#2371 Replace poa.infura.io -> core.poa.network for POA Network
  common/libs/nodes/configs.ts
Labels: 2019-02-01

#2233 Allow BIP49 dpath
  common/config/dpaths.ts
  spec/libs/validators.spec.ts
Labels: Release: 2019-02-07

#2358 add ARTIS sigma1 & tau1 networks ( https://artis.eco )
  common/config/contracts/artis_sigma1.json
  common/config/contracts/artis_tau1.json
  common/config/contracts/index.ts
  common/config/dpaths.ts
  common/config/tokens/artis_sigma1.json
  common/config/tokens/artis_tau1.json
  common/config/tokens/index.ts
  common/features/config/__snapshots__/sagas.spec.ts.snap
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  shared/types/network.d.ts
Labels: Release: 2019-02-07

#2359 Fix issue #2354
  common/translations/lang/ar.json
  common/translations/lang/de.json
  common/translations/lang/el.json
  common/translations/lang/en.json
  common/translations/lang/es.json
  common/translations/lang/fi.json
  common/translations/lang/fr.json
  common/translations/lang/ht.json
  common/translations/lang/hu.json
  common/translations/lang/id.json
  common/translations/lang/it.json
  common/translations/lang/ja.json
  common/translations/lang/ko.json
  common/translations/lang/nl.json
  common/translations/lang/no.json
  common/translations/lang/pl.json
  common/translations/lang/pt.json
  common/translations/lang/ru.json
  common/translations/lang/sk.json
  common/translations/lang/sl.json
  common/translations/lang/sv.json
  common/translations/lang/tr.json
  common/translations/lang/vi.json
  common/translations/lang/zhcn.json
  common/translations/lang/zhtw.json
Labels: Release: 2019-02-07

#2362 Fix ens subdomain resolution
  common/features/ens/helpers.ts
  common/features/transaction/sagas.ts
Labels: Release: 2019-02-07, status: approved by qa

#2363 Fixed data field by auto-opening advanced tab on `data` prefilled field.
  common/components/TXMetaDataPanel/TXMetaDataPanel.tsx
  common/utils/helpers.ts
Labels: Release: 2019-02-07, status: approved by qa

#2390 Update Trezor Connect
  common/libs/wallet/deterministic/trezor.ts
  common/typescript/trezor-connect.d.ts
  common/vendor/trezor-connect.js
Labels: release: 2019-02-22, status: approved by qa

#2388 Update logo-shapeshift.svg
  common/assets/images/logo-shapeshift-no-text-white.svg
  common/assets/images/logo-shapeshift-no-text.svg
  common/assets/images/logo-shapeshift.svg
  common/assets/images/shapeshift-dark.svg
  common/components/Header/components/Navigation.scss
Labels: release: 2019-02-22, status: approved by qa

#2384 Feature/goerli network
  common/components/NetworkSelector/NetworkSelector.tsx
  common/config/contracts/goerli.json
  common/config/contracts/index.ts
  common/config/tokens/goerli.json
  common/config/tokens/index.ts
  common/containers/Sidebar/helpers.ts
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  common/libs/nodes/index.ts
  shared/types/network.d.ts
Labels: release: 2019-02-22, status: approved by qa

#2395 Fix csp 2
  webpack_config/makeConfig.js
Labels: release: 2019-02-28

#2405 Trezor v7 + CSP Fix
  common/libs/wallet/deterministic/trezor.ts
  common/typescript/trezor-connect.d.ts
  common/vendor/trezor-connect.js
  package.json
  webpack_config/makeConfig.js
  yarn.lock
Labels: release: 2019-02-28, status: approved by qa

#2402 Fixed gas price Bug
  .nvmrc
  common/components/TXMetaDataPanel/components/AdvancedGas.tsx
  common/libs/validators.ts
Labels: release: 2019-02-28, status: approved by qa
