Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-09, with the labels that each got.

#2733 ConfirmTx / TxReceipt panel design Additions
  common/v2/components/Amount.scss
  common/v2/components/Amount.tsx
  common/v2/components/CopyableCodeBlock.tsx
  common/v2/components/index.ts
  common/v2/features/SendAssets/components/ConfirmTransaction.scss
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/components/TransactionReceipt.scss
  common/v2/features/SendAssets/components/TransactionReceipt.tsx
  common/v2/features/SendAssets/components/displays/TransactionDetailsDisplay.scss
  common/v2/features/SendAssets/components/displays/TransactionDetailsDisplay.tsx
  common/v2/features/SendAssets/components/displays/TransactionIntermediaryDisplay.tsx
  common/v2/features/SendAssets/components/displays/index.ts
  common/v2/features/SendAssets/types.ts
Labels: status: ready for review

#2734 Sreckosmodis/ch2535/revert https GitHub com mycryptohq mycrypto
  common/v2/components/DashboardPanel.scss
  common/v2/components/DashboardPanel.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.scss
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  webpack_config/makeConfig.js
Labels: status: ready for review, type: GAU

#2741 Conversion bug fix (overflow/underflow errors)
  common/v2/services/Store/Account/helpers.ts
  common/v2/services/Store/BalanceService.tsx
  common/v2/utils/convert.tsx
Labels: status: ready for review, type: issue

#2736 re-enabled validation for all send fields
  common/translations/lang/en.json
  common/v2/features/SendAssets/components/SendAssetsForm.scss
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/components/validators/validators.ts
  common/v2/services/EthService/index.ts
  common/v2/services/EthService/validators.ts
Labels: status: ready for review

#2748 Fix StoreProvider Bugs
  common/v2/services/Store/StoreProvider.tsx
Labels: wip

#2759 Added hardware wallet signing
  common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/index.ts
  common/v2/features/SendAssets/index.ts
Labels: wip
