Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-03, with the labels that each got.

#2396 Added additional products to footer
  common/components/Footer/NewFooter/components/Linkset.tsx
Labels: release: 2019-02-28

#2400 Add support TomoChain Mainnet
  common/config/dpaths.ts
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
Labels: release: 2019-02-28

#2401 Added security.txt and branching model convention
  README.md
  static/.well-known/security.txt
Labels: release: 2019-02-28

#2404 Add analytics and events
  common/Root.tsx
  common/components/ElectronNav/LanguageSelect.tsx
  common/components/Footer/NewFooter/components/DonateAndSubscribe.tsx
  common/components/Footer/NewFooter/components/Linkset.tsx
  common/components/Footer/NewFooter/components/SocialsAndLegal.tsx
  common/components/Footer/NewFooter/components/Subscribe.tsx
  common/components/Header/NewHeader/components/DesktopHeader.tsx
  common/components/Header/NewHeader/components/MobileHeader.tsx
  common/components/Header/index.tsx
  common/containers/Sidebar/components/SelectLanguage.tsx
  common/features/configureStore.ts
  common/v2/features/Layout/Footer/components/DonateAndSubscribe.tsx
  common/v2/features/Layout/Footer/components/Linkset.tsx
  common/v2/features/Layout/Footer/components/SocialsAndLegal.tsx
  common/v2/features/Layout/Footer/components/Subscribe.tsx
  common/v2/services/Analytics/Analytics.spec.ts
  common/v2/services/Analytics/Analytics.ts
  common/v2/services/Analytics/constants.ts
  common/v2/services/Analytics/index.ts
  common/v2/services/Analytics/types.ts
  common/v2/services/index.ts
Labels: status: ready for review, type: GAU

#2410 Version number change
  common/api/gas.ts
  common/config/dpaths.ts
  common/config/tokens/eth.json
  common/features/config/__snapshots__/sagas.spec.ts.snap
  common/features/config/networks/static/reducer.ts
  common/features/ens/sagas.ts
  common/libs/nodes/configs.ts
  package.json
  shared/types/network.d.ts
Labels: release: 1.6.1, status: approved by qa, status: ready to merge

#2443 Fix for Trezor Firmware 1.8.0 bug.
  shared/enclave/server/wallets/msg-config.ts
  shared/enclave/server/wallets/trezor.ts
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2442 API Gateway proxy updates
  common/api/rates.ts
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2441 update ledger packages
  .travis.yml
  jest_config/setupJest.js
  package.json
  webpack_config/webpack.electron-dev.js
  yarn.lock
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2438 fix press email link
  common/components/Footer/NewFooter/components/Linkset.tsx
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2437 Fix Pirl Poseidon Explorer links & add node admin contracts
  common/config/contracts/index.ts
  common/config/contracts/pirl.json
  common/features/config/networks/static/reducer.ts
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2207 Ak 2124 disabled verify for invalid address
  common/containers/Tabs/SignAndVerifyMessage/components/VerifyMessage/index.tsx
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2424 Update all references to the KB
  common/components/NonceField.tsx
  common/components/WalletDecrypt/WalletDecrypt.tsx
  common/components/WalletDecrypt/components/Trezor.tsx
  common/config/helpArticles.ts
  common/translations/lang/ar.json
  common/translations/lang/de.json
  common/translations/lang/el.json
  common/translations/lang/en.json
  common/translations/lang/es.json
  common/translations/lang/fi.json
  common/translations/lang/fr.json
  common/translations/lang/ht.json
  common/translations/lang/hu.json
  common/translations/lang/id.json
  common/translations/lang/it.json
  common/translations/lang/ja.json
  common/translations/lang/ko.json
  common/translations/lang/nl.json
  common/translations/lang/no.json
  common/translations/lang/pl.json
  common/translations/lang/pt.json
  common/translations/lang/ru.json
  common/translations/lang/sk.json
  common/translations/lang/sl.json
  common/translations/lang/sv.json
  common/translations/lang/tr.json
  common/translations/lang/vi.json
  common/translations/lang/zhcn.json
  common/translations/lang/zhtw.json
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2430 Add OpenWeb Network Contract and ABI
  common/config/contracts/eth.json
  common/config/tokens/eth.json
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2434 Update package description
  package.json
Labels: release: 1.6.2, status: ready to merge

#2432 UBQ: update node url, update explorer url
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2427 Fix chain nonce bug
  common/features/transaction/network/sagas.spec.ts
  common/features/transaction/network/sagas.ts
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2435 Run linters on commit
  package.json
  yarn.lock
Labels: release: 1.6.2, status: approved by qa, status: ready to merge

#2419 Feature/download desktop app
  common/translations/lang/en.json
  common/v2/components/ContentPanel.scss
  common/v2/components/ContentPanel.tsx
  common/v2/features/CreateWallet/routes.tsx
  common/v2/features/DownloadApp/DownloadApp.scss
  common/v2/features/DownloadApp/DownloadApp.tsx
  common/v2/features/DownloadApp/constants.ts
  common/v2/features/DownloadApp/helpers.ts
  common/v2/features/DownloadApp/index.ts
  common/v2/features/DownloadApp/routes.ts
  common/v2/features/DownloadApp/types.ts
  common/v2/services/Analytics/constants.ts
  common/v2/services/Github/Github.ts
  common/v2/services/Github/constants.ts
  common/v2/services/Github/index.ts
  common/v2/services/Github/types.ts
  common/v2/services/index.ts
Labels: status: approved by qa, status: ready to merge, type: GAU
