Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-08, with the labels that each got.

#2698 Remove unused v1 features
  common/AppRouter.tsx
  common/v2/features/Dashboard/Dashboard.tsx
  common/v2/features/Dashboard/NotificationsPanel/NotificationsPanel.tsx
  common/v2/features/Layout/Header/constants.ts
Labels: status: ready for review, type: GAU

#2702 Force production build to use dev environment css loaders temporarily
  webpack_config/makeConfig.js
Labels: status: ready for review

#2686 Fix ethersjs spam network issue
  common/v2/config/networks/globalProvider.ts
  common/v2/config/networks/providerHandler.ts
Labels: status: ready for review

#2697 release 1.7.1
  package.json
Labels: Release Tag

#2695 Format transaction values into valid tx
  common/v2/config/index.ts
  common/v2/config/networks/index.ts
  common/v2/features/AddAccount/AddAccount.scss
  common/v2/features/AddAccount/components/LedgerNano.tsx
  common/v2/features/AddAccount/components/Mnemonic.tsx
  common/v2/features/AddAccount/components/SafeT.tsx
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/AddAccount/components/Trezor.tsx
  common/v2/features/ReceiveAssets/ReceiveAssets.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.scss
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/SignTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Mnemonic.tsx
  common/v2/features/SendAssets/components/TransactionReceipt.tsx
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
  common/v2/features/SendAssets/components/fields/AssetDropdown.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/helpers.ts
  common/v2/features/SendAssets/index.ts
  common/v2/features/SendAssets/process.ts
  common/v2/features/SendAssets/stateFactory.tsx
  common/v2/features/SendAssets/types.ts
  common/v2/features/Wallets/web3/web3.ts
  common/v2/services/ApiService/Gas/gasPriceFunctions.tsx
  common/v2/services/ApiService/Gas/index.tsx
  common/v2/services/ApiService/index.ts
  common/v2/services/EthService/contracts/index.ts
  common/v2/services/EthService/contracts/token.ts
  common/v2/services/EthService/index.ts
  common/v2/services/EthService/utils/index.ts
  common/v2/services/EthService/utils/makeTransaction.ts
  common/v2/services/EthService/utils/units.ts
  common/v2/services/Store/Account/AccountProvider.tsx
  common/v2/services/Store/Account/helpers.ts
  common/v2/services/Store/Account/index.ts
  common/v2/services/Store/Asset/helpers.ts
  common/v2/services/Store/Asset/index.ts
  common/v2/services/Store/LocalCache/LocalCache.ts
  common/v2/services/Store/Network/helpers.ts
  common/v2/services/index.ts
  common/v2/utils/formatters.ts
  common/v2/utils/index.ts
  common/v2/utils/typeGuards.ts
  webpack_config/makeConfig.js
Labels: status: ready for review

#2693 working ens resolution
  common/translations/lang/en.json
  common/v2/components/ENSStatus.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/helpers.ts
  common/v2/features/SendAssets/stateFactory.tsx
  common/v2/features/SendAssets/types.ts
  common/v2/services/EthService/ens/contracts/AbiFunc.d.ts
  common/v2/services/EthService/ens/contracts/auction/auction.d.ts
  common/v2/services/EthService/ens/contracts/auction/auction.json
  common/v2/services/EthService/ens/contracts/auction/outputMappings.ts
  common/v2/services/EthService/ens/contracts/deed/deed.d.ts
  common/v2/services/EthService/ens/contracts/deed/deed.json
  common/v2/services/EthService/ens/contracts/deed/outputMappings.ts
  common/v2/services/EthService/ens/contracts/index.ts
  common/v2/services/EthService/ens/contracts/registry/outputMappings.ts
  common/v2/services/EthService/ens/contracts/registry/registry.d.ts
  common/v2/services/EthService/ens/contracts/registry/registry.json
  common/v2/services/EthService/ens/contracts/resolver/outputMappings.ts
  common/v2/services/EthService/ens/contracts/resolver/resolver.d.ts
  common/v2/services/EthService/ens/contracts/resolver/resolver.json
  common/v2/services/EthService/ens/index.ts
  common/v2/services/EthService/ens/networkConfigs/index.ts
  common/v2/services/EthService/ens/networkConfigs/main.json
  common/v2/services/EthService/ens/networkConfigs/rinkeby.json
  common/v2/services/EthService/ens/networkConfigs/ropsten.json
  common/v2/services/EthService/ens/networkConfigs/rsk.json
  common/v2/services/EthService/ens/validators.ts
  common/v2/services/EthService/index.ts
Labels: status: ready for review

#2710 Wrapping up send form effects (does not include validation)
  common/v2/components/AccountOption.tsx
  common/v2/components/AccountSummary.tsx
  common/v2/config/index.ts
  common/v2/features/SendAssets/components/SendAssetsForm.scss
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/displays/TransactionFeeDisplay.tsx
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
  common/v2/features/SendAssets/components/fields/AssetDropdown.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/components/fields/GasLimitField.tsx
  common/v2/features/SendAssets/components/validators/validators.ts
  common/v2/features/SendAssets/helpers.ts
  common/v2/services/EthService/index.ts
  common/v2/services/EthService/utils/index.ts
  common/v2/services/EthService/utils/units.ts
  common/v2/services/Store/AddressBook/AddressBookProvider.tsx
Labels: status: ready for review

#2716 Use self-hosted CDN for asset icons
  common/v2/components/AssetIcon.tsx
  webpack_config/makeConfig.js
Labels: status: ready for review

#2713 Added additional information to Confirm Transaction Panel
  common/v2/features/SendAssets/components/ConfirmTransaction.scss
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/stateFactory.tsx
  common/v2/features/SendAssets/types.ts
  common/v2/services/Store/AddressBook/AddressBookProvider.tsx
Labels: status: ready for review

#2721 Fix/travis build times
  .travis.yml
  package.json
  travis-scripts/test-linux.sh
  travis-scripts/test-osx.sh
Labels: status: ready for review, type: GAU

#2712 adding FUNDING.yml
  .github/FUNDING.yml
Labels: status: ready to merge

#2718 Display tx receipt on Transaction Receipt Panel
  common/v2/components/TimeElapsedCounter.tsx
  common/v2/components/index.ts
  common/v2/features/SendAssets/components/ConfirmTransaction.scss
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx
  common/v2/features/SendAssets/components/TransactionReceipt.scss
  common/v2/features/SendAssets/components/TransactionReceipt.tsx
  common/v2/features/SendAssets/components/displays/TransactionDetailsDisplay.scss
  common/v2/features/SendAssets/components/displays/TransactionDetailsDisplay.tsx
  common/v2/features/SendAssets/components/displays/index.ts
  common/v2/features/SendAssets/helpers.ts
  common/v2/features/SendAssets/stateFactory.tsx
  common/v2/services/EthService/index.ts
  common/v2/services/EthService/network/providerHandler.ts
  common/v2/services/EthService/utils/index.ts
  common/v2/services/EthService/utils/providerWrappers.ts
Labels: status: ready for review

#2727 Fixes for get-account-balance usability
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
  common/v2/features/SendAssets/components/fields/AssetDropdown.tsx
  common/v2/services/EthService/network/helpers.ts
  common/v2/services/Store/Asset/helpers.ts
  common/v2/services/Store/LocalCache/seedCache.ts
Labels: status: ready for review
