Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-01, with the labels that each got.

#2294 Use RSK checksum on contract response
  common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
Labels: release: 2019-01-10, status: approved by qa

#2298 Fixes RSK issues with wallets availability
  common/features/config/networks/static/reducer.ts
  common/features/config/selectors.ts
Labels: release: 2019-01-10, status: approved by qa

#2305 Fixes arbitrary value for gasPrice
  common/components/TXMetaDataPanel/TXMetaDataPanel.tsx
Labels: release: 2019-01-10, status: approved by qa

#2323 Refreshes balances when token is chosen in combobox
  common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
Labels: release: 2019-01-10, status: approved by qa

#2340 [FEATURE] Improve token transfer flow
  common/components/AwaitingMiningModal/index.tsx
  common/components/ConfirmationModal/components/Body/Body.tsx
  common/components/ConfirmationModal/components/Body/components/Addresses.tsx
  common/components/ExtendedNotifications/TransactionSucceeded.tsx
  common/components/TXMetaDataPanel/components/AdvancedGas.tsx
  common/components/index.ts
  common/containers/Tabs/ScheduleTransaction/components/SchedulingModals.scss
  common/containers/Tabs/ScheduleTransaction/components/SchedulingModals.tsx
  common/containers/Tabs/ScheduleTransaction/components/SendScheduleTransactionButton.tsx
  common/containers/Tabs/ScheduleTransaction/components/index.ts
  common/containers/Tabs/SendTransaction/components/Fields/Fields.tsx
  common/features/schedule/actions.ts
  common/features/schedule/helpers.ts
  common/features/schedule/reducer.ts
  common/features/schedule/sagas.ts
  common/features/schedule/selectors.ts
  common/features/schedule/types.ts
  common/features/transaction/network/sagas.spec.ts
  common/features/transaction/network/sagas.ts
  common/features/transaction/sign/sagas.ts
  common/libs/scheduling/index.ts
  common/translations/lang/en.json
Labels: release: 2019-01-10, status: approved by qa

#2343 Removed etc - epool node
  common/libs/nodes/configs.ts
Labels: release: 2019-01-10, status: approved by qa

#2346 Fix CSP err and add 0x Instant Err message
  common/v2/features/BuyAndExchange/ZeroEx/ZeroEx.tsx
  webpack_config/makeConfig.js
Labels: status: approved by qa

#2293 Rsk Name Service integration
  common/components/AddressFieldFactory/AddressInputFactory.tsx
  common/config/contracts/rsk.json
  common/features/config/selectors.ts
  common/features/ens/helpers.ts
  common/features/ens/selectors.ts
  common/features/transaction/sagas.spec.ts
  common/features/transaction/sagas.ts
  common/libs/ens/networkConfigs/index.ts
  common/libs/ens/networkConfigs/rsk.json
  common/libs/validators.ts
  common/translations/lang/en.json
  common/translations/lang/fr.json
  common/translations/lang/ko.json
  spec/libs/validators.spec.ts
Labels: release: 2019-01-10
