Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-06, with the labels that each got.

#2605 Advanced Transaction Field tweaks / refactor
  common/v2/features/SendAssets/components/TransactionFormData.scss
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/fields/DataField.tsx
  common/v2/features/SendAssets/components/fields/GasLimitField.tsx
  common/v2/features/SendAssets/components/fields/GasPriceField.tsx
  common/v2/features/SendAssets/components/fields/NonceField.tsx
  common/v2/features/SendAssets/components/index.ts
  common/v2/features/SendAssets/components/validators/index.ts
  common/v2/features/SendAssets/components/validators/validators.ts
Labels: type: GAU

#2609 Added Test Accounts during Initialization of LC
  common/translations/lang/en.json
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletNotAddedNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/index.ts
  common/v2/features/DevTools/DevTools.tsx
  common/v2/libs/assetOptions.ts
  common/v2/libs/assets/assets.ts
  common/v2/libs/assets/index.ts
  common/v2/libs/index.ts
  common/v2/providers/NotificationsProvider/constants.ts
  common/v2/services/Account/types.ts
  common/v2/services/Asset/Asset.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
Labels: type: GAU

#2599 MetaMask sign transaction flow
  common/v2/config/data.tsx
  common/v2/features/AddAccount/components/NetworkSelectPanel.tsx
  common/v2/features/Dashboard/components/AccountDropdown.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/SendAssets/components/SignTransaction.scss
  common/v2/features/SendAssets/components/SignTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/MetaMask.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/index.ts
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/TransactionReceipt.tsx
  common/v2/features/SendAssets/types.ts
  common/v2/libs/transaction/process.ts
  package.json
  shared/types/util.d.ts
  yarn.lock
Labels: status: ready for review, type: GAU

#2610 ev/assets dropdown
  common/translations/lang/en.json
  common/v2/components/AccountSummary.tsx
  common/v2/components/AssetIcon.tsx
  common/v2/components/AssetSummary.tsx
  common/v2/components/Dropdown.tsx
  common/v2/components/Typography.tsx
  common/v2/components/index.ts
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
  common/v2/features/SendAssets/components/fields/AssetDropdown.tsx
  common/v2/features/SendAssets/components/fields/AssetField.tsx
  common/v2/features/SendAssets/components/fields/index.ts
  common/v2/features/SendAssets/types.ts
  common/v2/libs/transaction/process.ts
  common/v2/types/asset.tsx
  common/v2/types/index.ts
  common/v2/types/symbols.ts
  package.json
  yarn.lock
Labels: type: GAU

#2541 Chore/rhl
  .babelrc
  README.md
  common/Root.tsx
  common/index.tsx
  package.json
  webpack_config/config.js
  webpack_config/devServer.js
  webpack_config/electron-main.dev.js
  webpack_config/electron-renderer.dev.js
  webpack_config/makeConfig.js
  webpack_config/webpack.dev.js
  webpack_config/webpack.electron-prod.js
  webpack_config/webpack.rhl.js
  yarn.lock
Labels: release: 1.6.8, status: approved by qa, status: ready to merge

#2596 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release: 1.6.8

#2615 EtherInc (ETI) support - branch rebase
  common/config/dpaths.ts
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  shared/types/network.d.ts
Labels: release: 1.6.8, status: ready for qa, status: ready to merge

#2586 Update rsk_testnet.json
  common/config/contracts/rsk_testnet.json
Labels: release: 1.6.8

#2616 travisCI Slack integration
  .travis.yml
Labels: release: 1.6.8, status: approved by qa, status: ready to merge

#2497 Overhaul/Settings flow
  common/Root.tsx
  common/translations/lang/en.json
  common/v2/components/Button.tsx
  common/v2/components/ContentPanel.tsx
  common/v2/components/Link.tsx
  common/v2/components/RouterLink.tsx
  common/v2/components/index.ts
  common/v2/features/Dashboard/Settings/Export/Downloader.tsx
  common/v2/features/Dashboard/Settings/Export/Export.tsx
  common/v2/features/Dashboard/Settings/Export/index.ts
  common/v2/features/Dashboard/Settings/Import/Import.tsx
  common/v2/features/Dashboard/Settings/Import/components/ImportBox.tsx
  common/v2/features/Dashboard/Settings/Import/components/ImportSuccess.tsx
  common/v2/features/Dashboard/Settings/Import/components/index.ts
  common/v2/features/Dashboard/Settings/Import/index.ts
  common/v2/features/Dashboard/Settings/Settings.scss
  common/v2/features/Dashboard/Settings/Settings.tsx
  common/v2/features/Dashboard/Settings/components/AddToAddressBook.scss
  common/v2/features/Dashboard/Settings/components/AddToAddressBook.tsx
  common/v2/features/Dashboard/Settings/components/AddressBook.tsx
  common/v2/features/Dashboard/Settings/components/GeneralSettings.scss
  common/v2/features/Dashboard/Settings/components/GeneralSettings.tsx
  common/v2/features/Dashboard/Settings/components/YourAccounts.tsx
  common/v2/features/Dashboard/Settings/components/index.ts
  common/v2/features/Dashboard/Settings/index.ts
  common/v2/features/Dashboard/Settings/routes.ts
  common/v2/features/Dashboard/routes.ts
  common/v2/features/Layout/Header/constants.ts
  common/v2/features/Layout/Layout.tsx
  common/v2/features/index.ts
  common/v2/features/registry.json
  common/v2/providers/LockScreenProvider/LockScreenProvider.tsx
  common/v2/providers/SettingsProvider/SettingsProvider.tsx
  common/v2/services/Analytics/constants.ts
  common/v2/services/Settings/Settings.ts
  yarn.lock
Labels: type: GAU, wip

#2623 Sender Address Filtering
  common/translations/lang/en.json
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/SendAssets/components/displays/TransactionValuesDisplay.tsx
  common/v2/features/SendAssets/components/displays/index.ts
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
Labels: type: GAU

#2632 Fixes to accounts table and dashboard dropdown rendering
  common/v2/features/Dashboard/Dashboard.tsx
  common/v2/features/Dashboard/Settings/Settings.tsx
  common/v2/features/Dashboard/components/AccountDropdown.tsx
  common/v2/features/Dashboard/components/AccountList.tsx
Labels: status: ready to merge, type: GAU

#2617 Release/1.6.8
  package.json
Labels: release: 1.6.8

#2607 Remove Moon Mode Toggle
  common/v2/features/Layout/Footer/Footer.scss
  common/v2/features/Layout/Footer/components/LogoBox.scss
  common/v2/features/Layout/Footer/components/LogoBox.tsx
Labels: type: GAU

#2635 ethers.js class provider
  common/v2/config/networks/globalProvider.ts
  common/v2/config/networks/index.ts
  common/v2/config/networks/providerHandler.ts
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/features/SendAssets/components/TransactionFormData.tsx
  common/v2/features/Wallets/web3/web3.ts
  common/v2/libs/accounts/accounts.ts
  common/v2/libs/nodes/rpc/requests.ts
  common/v2/libs/transaction/process.ts
  common/v2/libs/units.ts
  common/v2/services/Account/types.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
Labels: wip

#2608 Remove fiat dropdown for MVP
  common/v2/features/Dashboard/components/WalletBreakdown.scss
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
Labels: type: GAU

#2631 Ev/default fields
  common/translations/lang/en.json
  common/v2/components/AccountSummary.tsx
  common/v2/components/AssetIcon.tsx
  common/v2/components/Currency.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.scss
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/displays/TransactionValuesDisplay.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/components/fields/GasPriceSlider.scss
  common/v2/features/SendAssets/components/fields/GasPriceSlider.tsx
  common/v2/features/SendAssets/components/fields/RecipientAddressField.tsx
  common/v2/features/SendAssets/components/fields/index.ts
  common/v2/features/SendAssets/components/index.ts
  common/v2/types/asset.tsx
  common/v2/types/symbols.ts
  common/v2/utils/symbolIcon.ts
  package.json
  yarn.lock
Labels: status: ready to merge, type: GAU

#2625 Ethers global providers
  common/v2/config/networks/globalProvider.ts
  common/v2/config/networks/index.ts
  common/v2/config/networks/providerHandler.ts
  common/v2/config/networks/providerOptions.ts
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/SignTransaction.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.scss
  common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.tsx
  common/v2/features/SendAssets/components/SignTransactionWallets/index.ts
  common/v2/features/Wallets/web3/web3.ts
  common/v2/libs/accounts/accounts.ts
  common/v2/libs/helpers.ts
  common/v2/libs/nodes/rpc/requests.ts
  common/v2/libs/transaction/process.ts
  common/v2/libs/units.ts
  common/v2/services/Account/types.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
Labels: status: ready for review, type: GAU

#2629 New paper wallet layout
  common/assets/images/icn-download.svg
  common/assets/images/icn-keystore.svg
  common/assets/images/icn-lock-safety.svg
  common/assets/images/logo-mycrypto-transparent.png
  common/components/PaperWallet/index.tsx
  common/components/ui/Spinner.scss
  common/config/navigation.ts
  common/translations/lang/en.json
  common/v2/components/ErrorMessages/InlineErrors.tsx
  common/v2/components/ExtendedContentPanel.tsx
  common/v2/components/InputField.tsx
  common/v2/components/NetworkSelectDropdown.tsx
  common/v2/components/PaperWallet.tsx
  common/v2/components/PrintPaperWalletButton.tsx
  common/v2/components/index.ts
  common/v2/config/data.tsx
  common/v2/config/navigation.ts
  common/v2/features/AddAccount/components/NetworkSelectPanel.tsx
  common/v2/features/AddAccount/components/Web3Provider.tsx
  common/v2/features/AddAccount/stories.tsx
  common/v2/features/CreateWallet/CreateWallet.scss
  common/v2/features/CreateWallet/CreateWallet.tsx
  common/v2/features/CreateWallet/Keystore/Keystore.tsx
  common/v2/features/CreateWallet/Keystore/components/GenerateKeystoreFilePanel.scss
  common/v2/features/CreateWallet/Keystore/components/GenerateKeystoreFilePanel.tsx
  common/v2/features/CreateWallet/Keystore/components/KeystoreProvider.tsx
  common/v2/features/CreateWallet/Keystore/components/MakeBackupPanel.tsx
  common/v2/features/CreateWallet/Keystore/components/SaveKeystoreFilePanel.scss
  common/v2/features/CreateWallet/Keystore/components/SaveKeystoreFilePanel.tsx
  common/v2/features/CreateWallet/Keystore/components/VerifyKeystorePanel.tsx
  common/v2/features/CreateWallet/Keystore/components/index.ts
  common/v2/features/CreateWallet/Keystore/constants.ts
  common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx
  common/v2/features/CreateWallet/Mnemonic/components/BackUpPhrasePanel.scss
  common/v2/features/CreateWallet/Mnemonic/components/BackUpPhrasePanel.tsx
  common/v2/features/CreateWallet/Mnemonic/components/ConfirmPhrasePanel.scss
  common/v2/features/CreateWallet/Mnemonic/components/ConfirmPhrasePanel.tsx
  common/v2/features/CreateWallet/Mnemonic/components/GeneratePhrasePanel.scss
  common/v2/features/CreateWallet/Mnemonic/components/GeneratePhrasePanel.tsx
  common/v2/features/CreateWallet/Mnemonic/components/MnemonicProvider.tsx
  common/v2/features/CreateWallet/Mnemonic/components/index.ts
  common/v2/features/CreateWallet/components/SelectNetworkPanel.scss
  common/v2/features/CreateWallet/components/SelectNetworkPanel.tsx
  common/v2/features/CreateWallet/components/withAccountAndNotificationsContext.tsx
  common/v2/features/CreateWallet/routes.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/PrintPaperWalletNotification.tsx
  common/v2/features/DownloadApp/DownloadApp.tsx
  common/v2/features/ScreenLock/ScreenLockLocked/ScreenLockLocked.tsx
  common/v2/features/ScreenLock/ScreenLockNew/ScreenLockNew.tsx
  common/v2/features/ScreenLock/components/InputField.tsx
  package.json
  yarn.lock
Labels: type: GAU

#2641 Nonce Lookup for Account Selection in Send Assets
  common/v2/features/Nonce/index.ts
  common/v2/features/Nonce/nonceFunctions.ts
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/index.ts
Labels: status: ready for review, type: GAU

#2606 Remove recent transactions for MVP
  common/Root.tsx
  common/v2/features/Dashboard/Dashboard.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/providers/DevModeProvider/DevModeProvider.tsx
  common/v2/providers/DevModeProvider/index.ts
  common/v2/providers/index.ts
Labels: type: GAU, wip

#2648 Validation changes & other cleanup stuff
  common/translations/lang/en.json
  common/v2/components/ENSStatus.tsx
  common/v2/components/index.ts
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
  common/v2/features/SendAssets/components/fields/EthAddressField.tsx
  common/v2/features/SendAssets/components/fields/GasLimitField.tsx
  common/v2/features/SendAssets/components/validators/validators.ts
  common/v2/libs/formatters.ts
  common/v2/libs/validators.ts
Labels: type: GAU

#2624 Address Book Labeling in add-existing-account
  common/v2/features/AddAccount/components/SaveAndRedirect.tsx
  common/v2/features/CreateWallet/Keystore/Keystore.tsx
  common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx
  common/v2/features/Dashboard/Settings/components/AddToAddressBook.tsx
  common/v2/features/Dashboard/components/AccountDropdown.tsx
  common/v2/features/Dashboard/components/AccountList.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/features/DevTools/ToolsAccountList.tsx
  common/v2/features/SendAssets/SendAssets.tsx
  common/v2/features/SendAssets/components/ConfirmTransaction.tsx
  common/v2/libs/accounts/accounts.ts
  common/v2/libs/addressbook/addressbook.ts
  common/v2/libs/addressbook/index.ts
  common/v2/libs/index.ts
  common/v2/services/Account/types.ts
  common/v2/services/AddressBook/AddressBook.ts
  common/v2/services/AddressBook/types.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
Labels: status: ready for review, type: GAU
