Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-07, with the labels that each got.

#2643 Header language switcher and fixes
  common/Root.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletAddedNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletCreatedNotification.tsx
  common/v2/features/Dashboard/NotificationsPanel/components/WalletNotAddedNotification.tsx
  common/v2/features/Dashboard/constants.ts
  common/v2/features/Dashboard/routes.ts
  common/v2/features/Drawer/Drawer.scss
  common/v2/features/Drawer/Drawer.tsx
  common/v2/features/Drawer/index.ts
  common/v2/features/Drawer/screens/SelectLanguage.tsx
  common/v2/features/Drawer/screens/index.ts
  common/v2/features/Home/components/BottomActionPanel.tsx
  common/v2/features/Layout/Footer/components/Linkset.tsx
  common/v2/features/Layout/Header/Header.tsx
  common/v2/features/Layout/Header/constants.ts
  common/v2/features/constants.ts
Labels: type: GAU

#2646 Add Auxilium crypto support
  common/config/dpaths.ts
  common/features/config/__snapshots__/sagas.spec.ts.snap
  common/features/config/networks/static/reducer.ts
  common/libs/nodes/configs.ts
  shared/types/network.d.ts
Labels: Release: 1.7.0, status: approved by qa, status: ready to merge

#2653 Feature/homepage routing and links
  common/Root.tsx
  common/containers/OnboardingModal/OnboardingModal.scss
  common/containers/OnboardingModal/OnboardingModal.tsx
  common/containers/OnboardingModal/components/HardwareWalletChoice.scss
  common/containers/OnboardingModal/components/HardwareWalletChoice.tsx
  common/containers/OnboardingModal/components/OnboardingButton.scss
  common/containers/OnboardingModal/components/OnboardingButton.tsx
  common/containers/OnboardingModal/components/ProgressDots.scss
  common/containers/OnboardingModal/components/ProgressDots.tsx
  common/containers/OnboardingModal/components/index.ts
  common/containers/OnboardingModal/index.ts
  common/containers/OnboardingModal/slides/FirstSlide.tsx
  common/containers/OnboardingModal/slides/FourthSlide.scss
  common/containers/OnboardingModal/slides/FourthSlide.tsx
  common/containers/OnboardingModal/slides/SecondSlide.scss
  common/containers/OnboardingModal/slides/SecondSlide.tsx
  common/containers/OnboardingModal/slides/ThirdSlide.tsx
  common/containers/OnboardingModal/slides/index.ts
  common/features/configureStore.ts
  common/features/onboarding/actions.ts
  common/features/onboarding/index.ts
  common/features/onboarding/reducer.ts
  common/features/onboarding/selectors.ts
  common/features/onboarding/types.ts
  common/features/reducers.ts
  common/sass/mixins.scss
  common/v2/features/AddAccount/AddAccountFlow.tsx
  common/v2/features/AddAccount/routes.ts
  common/v2/features/Home/components/BottomActionPanel.tsx
  common/v2/features/Home/components/CompatibleWalletsPanel.tsx
  common/v2/features/Home/components/FeaturesPanel.tsx
  common/v2/features/Home/components/GetStartedPanel.tsx
  common/v2/features/Home/components/PeaceOfMindPanel.tsx
  common/v2/providers/LockScreenProvider/LockScreenProvider.tsx
  common/v2/routing/helpers.ts
  common/v2/routing/helpers.tsx
Labels: status: ready for review, type: GAU

#2638 Feature/banner ads
  common/assets/images/ads/Ledger_Desktop.png
  common/assets/images/ads/Ledger_Mobile.png
  common/assets/images/ads/ShapeShift_Mobile.png
  common/assets/images/ads/Shapeshift_Desktop.png
  common/assets/images/ads/Simplex_Desktop.png
  common/assets/images/ads/Simplex_Mobile.png
  common/assets/images/ads/Trezor_Desktop.png
  common/assets/images/ads/Trezor_Mobile.png
  common/v2/components/BannerAd/BannerAd.tsx
  common/v2/components/BannerAd/constants.ts
  common/v2/components/BannerAd/index.ts
  common/v2/features/Dashboard/Dashboard.tsx
  common/v2/services/Analytics/constants.ts
Labels: status: ready for review, type: GAU

#2656 Wallet breakdown
  common/assets/images/icn-add-assets.svg
  common/translations/lang/en.json
  common/v2/features/Dashboard/Settings/components/AddToAddressBook.tsx
  common/v2/features/Dashboard/components/AccountList.scss
  common/v2/features/Dashboard/components/AccountList.tsx
  common/v2/features/Dashboard/components/DashboardPanel.scss
  common/v2/features/Dashboard/components/DashboardPanel.tsx
  common/v2/features/Dashboard/components/RecentTransactionList.tsx
  common/v2/features/Dashboard/components/TokenList.scss
  common/v2/features/Dashboard/components/TokenList.tsx
  common/v2/features/Dashboard/components/WalletBreakdown.scss
  common/v2/features/Dashboard/components/WalletBreakdown.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/BalancesDetailView.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/BreakdownChart.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/NoAccountsSelected.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/NoAssets.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
  common/v2/features/Dashboard/components/WalletBreakdown/index.ts
  common/v2/features/Dashboard/components/WalletBreakdown/types.ts
  common/v2/features/Dashboard/components/index.ts
  common/v2/features/Layout/Header/Header.tsx
  common/v2/libs/accounts/accounts.ts
  common/v2/services/Analytics/constants.ts
  package.json
  yarn.lock
Labels: type: GAU

#2657 ev/exchange rate polling
  common/AppProviders.tsx
  common/Root.tsx
  common/components/index.ts
  common/containers/index.ts
  common/index.tsx
  common/v2/features/AddAccount/components/InsecureWalletWarning.tsx
  common/v2/features/AddAccount/components/Web3ProviderInstall.tsx
  common/v2/features/AddAccount/stories.tsx
  common/v2/libs/index.ts
  common/v2/libs/web-workers/index.ts
  common/v2/libs/web-workers/polling.service.tsx
  common/v2/libs/web-workers/polling.worker.tsx
  common/v2/providers/RatesProvider.tsx
  common/v2/providers/StoreProvider.tsx
  common/v2/providers/index.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/types/index.ts
  common/v2/types/rate.ts
  common/v2/utils/constants.tsx
  common/v2/utils/index.ts
  electron-app/main/index.ts
  jest_config/jest.config.json
  package.json
  yarn.lock
Labels: type: GAU

#2666 Bug/endless loop on add account
  common/v2/libs/addressbook/addressbook.ts
Labels: status: ready for review, type: GAU

#2658 release/1.7.0
  package.json
Labels: Release: 1.7.0

#2684 ev/fix dashboard and menu links
  common/AppRouter.tsx
  common/Root.tsx
  common/v2/components/BannerAd/constants.ts
  common/v2/components/index.ts
  common/v2/config/index.ts
  common/v2/config/links.ts
  common/v2/config/navigation.ts
  common/v2/config/routePaths.ts
  common/v2/features/AddAccount/AddAccountFlow.tsx
  common/v2/features/BuyAndExchange/BuyAndExchange.tsx
  common/v2/features/CreateWallet/CreateWallet.tsx
  common/v2/features/CreateWallet/Keystore/Keystore.tsx
  common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx
  common/v2/features/Dashboard/components/ActionTile.tsx
  common/v2/features/Dashboard/constants.ts
  common/v2/features/Drawer/screens/AccountScreen.tsx
  common/v2/features/Drawer/screens/UnlockScreen.tsx
  common/v2/features/Home/Home.tsx
  common/v2/features/Home/components/GetStartedPanel.tsx
  common/v2/features/Layout/Footer/Footer.scss
  common/v2/features/Layout/Footer/Footer.tsx
  common/v2/features/Layout/Footer/components/DonateAndSubscribe.scss
  common/v2/features/Layout/Footer/components/DonateAndSubscribe.tsx
  common/v2/features/Layout/Footer/components/Linkset.scss
  common/v2/features/Layout/Footer/components/Linkset.tsx
  common/v2/features/Layout/Footer/components/LogoBox.scss
  common/v2/features/Layout/Footer/components/LogoBox.tsx
  common/v2/features/Layout/Footer/components/SocialsAndLegal.scss
  common/v2/features/Layout/Footer/components/SocialsAndLegal.tsx
  common/v2/features/Layout/Footer/components/Subscribe.tsx
  common/v2/features/Layout/Footer/components/index.ts
  common/v2/features/Layout/Footer/index.ts
  common/v2/features/Layout/Header/Header.tsx
  common/v2/features/Layout/Header/constants.ts
  common/v2/features/Layout/Header/helpers.ts
  common/v2/features/Layout/Header/index.ts
  common/v2/features/Layout/Layout.tsx
  common/v2/features/Layout/index.ts
  common/v2/features/PageNotFound/PageNotFound.scss
  common/v2/features/PageNotFound/PageNotFound.tsx
  common/v2/features/PageNotFound/index.ts
  common/v2/features/index.ts
  common/v2/features/routes.tsx
  common/v2/providers/ScreenLockProvider/ScreenLockProvider.tsx
  common/v2/routing/DefaultHomeHandler.tsx
  common/v2/routing/LegacyRoutesHandler.tsx
  common/v2/routing/PageVisitAnalytics.tsx
  common/v2/routing/PrivateRoute.tsx
  common/v2/routing/helpers.tsx
  common/v2/routing/index.ts
  common/v2/routing/routes.tsx
  common/v2/types/index.ts
  common/v2/types/routes.ts
  common/v2/utils/constants.tsx
  common/v2/utils/useOnClickOutside.tsx
Labels: status: ready to merge, type: GAU

#2634 Receive flow that generates a EIP681 string and displays a QR code (CH #1741)
  .gitattributes
  common/AppProviders.tsx
  common/translations/lang/en.json
  common/v2/components/AccountOption.tsx
  common/v2/components/ContentPanel.tsx
  common/v2/components/PaperWallet.tsx
  common/v2/components/QRCode.tsx
  common/v2/components/index.ts
  common/v2/features/ReceiveAssets/ReceiveAssets.tsx
  common/v2/features/ReceiveAssets/components/AccountDropdown.tsx
  common/v2/features/ReceiveAssets/components/index.ts
  common/v2/features/ReceiveAssets/index.ts
  common/v2/features/RequestAssets/RequestAssets.scss
  common/v2/features/RequestAssets/RequestAssets.tsx
  common/v2/features/RequestAssets/index.ts
  common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
  common/v2/features/index.ts
  common/v2/routing/routes.tsx
  common/v2/services/EthService/utils/formatters.ts
  common/v2/utils/formatters.ts
  common/v2/utils/index.ts
  common/v2/utils/validators.ts
Labels: status: changes needed, type: GAU

#2692 Re-Added base assets on send flow assets-dropdown
  common/v2/features/SendAssets/components/SendAssetsForm.tsx
Labels: status: ready for review
