Repository MyCryptoHQ/MyCrypto, pull requests merged in 2019-04, with the labels that each got.

#2454 Feature/homepage
  common/assets/images/control-crypto-mobile.svg
  common/assets/images/control-crypto.svg
  common/assets/images/icn-champagne-2.svg
  common/assets/images/icn-dashboard.svg
  common/assets/images/icn-opensource.svg
  common/assets/images/icn-oval.svg
  common/assets/images/icn-protect.svg
  common/assets/images/icn-purple-swoosh.svg
  common/assets/images/icn-sparkles-1.svg
  common/assets/images/icn-sparkles-2.svg
  common/assets/images/icn-sparkles-3.svg
  common/assets/images/icn-sparkles-4.svg
  common/assets/images/icn-vault2.svg
  common/assets/images/manage-your-wallets-mobile.svg
  common/assets/images/manage-your-wallets.svg
  common/assets/images/returning.svg
  common/assets/images/title-illustration.svg
  common/assets/images/view-dashboard-mobile.svg
  common/assets/images/view-dashboard.svg
  common/assets/images/wallets/ledger-2.svg
  common/assets/images/wallets/metamask-2.svg
  common/assets/images/wallets/safe-t.png
  common/assets/images/wallets/trust-2.svg
  common/sass/variables/colors.scss
  common/sass/variables/grid.scss
  common/translations/lang/en.json
  common/v2/features/DownloadApp/DownloadApp.tsx
  common/v2/features/Home/Home.scss
  common/v2/features/Home/Home.tsx
  common/v2/features/Home/components/BottomActionPanel.tsx
  common/v2/features/Home/components/CompatibleWalletsPanel.tsx
  common/v2/features/Home/components/DownloadAppPanel.tsx
  common/v2/features/Home/components/FeaturesPanel.tsx
  common/v2/features/Home/components/GetStartedPanel.scss
  common/v2/features/Home/components/GetStartedPanel.tsx
  common/v2/features/Home/components/PeaceOfMindPanel.tsx
  common/v2/features/Home/components/SliderImports.scss
  common/v2/features/Home/components/TestimonialsPanel.tsx
  common/v2/features/Home/components/index.ts
  common/v2/features/Home/routes.ts
  common/v2/features/Layout/Header/Header.scss
  common/v2/features/Layout/Header/Header.tsx
  common/v2/features/Layout/Header/constants.ts
  common/v2/features/Layout/Layout.scss
  common/v2/features/constants.ts
  common/v2/features/helpers.ts
  common/v2/features/index.ts
  common/v2/services/Analytics/constants.ts
  package.json
  yarn.lock
Labels: status: approved by qa, status: ready to merge, type: GAU

#2493 Added basic logic for handling in add-existing-account-flow
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/services/Account/types.ts
  common/v2/services/LocalCache/constants.ts
Labels: type: GAU, wip

#2506 Reroute back button to beginning of add-account flow
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/Wallets/web3/web3.ts
Labels: status: ready to merge

#2511 Add createWithID Method
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/NodeOptions/NodeOptions.ts
  common/v2/services/NodeOptions/types.ts
Labels: type: GAU, wip

#2507 Re-Add and Enable view-only account type
  common/v2/features/AddAccount/AddAccount.tsx
Labels: type: GAU, wip

#2495 Add existing account views: Select Address
  common/api/rates.ts
  common/assets/images/next-page-button.svg
  common/assets/images/previous-page-button.svg
  common/components/AddressField.tsx
  common/components/BalanceSidebar/EquivalentValues.tsx
  common/components/WalletDecrypt/WalletDecrypt.scss
  common/components/ui/UnitDisplay.tsx
  common/config/dpaths.ts
  common/features/config/__snapshots__/sagas.spec.ts.snap
  common/features/config/networks/static/reducer.ts
  common/features/ens/helpers.ts
  common/features/rates/reducer.spec.ts
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/AddAccount/AddAccountStyles.scss
  common/v2/features/AddAccount/components/DeterministicWallets.scss
  common/v2/features/AddAccount/components/DeterministicWallets.tsx
  common/v2/features/AddAccount/components/DeterministicWalletsModal.tsx
  common/v2/features/AddAccount/components/LedgerNano.tsx
  common/v2/features/AddAccount/components/Mnemonic.tsx
  common/v2/features/AddAccount/components/SafeT.tsx
  common/v2/features/AddAccount/components/Trezor.tsx
  common/v2/features/AddAccount/components/index.ts
  common/v2/features/Dashboard/SendAssets/components/ConfirmTransaction.tsx
  common/v2/features/Dashboard/SendAssets/components/TransactionComplete.tsx
  common/v2/features/Dashboard/Settings/components/AddressBook.tsx
  common/v2/features/Dashboard/Settings/components/YourAccounts.tsx
  common/v2/features/Dashboard/components/AccountList.tsx
  common/v2/features/Dashboard/components/RecentTransactionList.tsx
  common/v2/features/Drawer/screens/AccountScreen.tsx
  jest_config/jest.config.json
  jest_config/jest.int.config.json
  package.json
  yarn.lock
Labels: type: GAU

#2509 No accounts flow
  common/Root.tsx
  common/assets/images/icn-sad-wallet.svg
  common/translations/lang/en.json
  common/v2/features/AddAccount/index.ts
  common/v2/features/NoAccounts/NoAccountAuth.tsx
  common/v2/features/NoAccounts/NoAccounts.tsx
  common/v2/features/NoAccounts/index.ts
  common/v2/features/NoAccounts/routes.ts
  common/v2/features/index.ts
  common/v2/features/registry.json
Labels: status: changes needed, type: GAU

#2528 Add-account flow default changes
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/Wallets/web3/web3.ts
  common/v2/libs/networks/index.ts
  common/v2/libs/networks/networks.ts
  common/v2/libs/networks/types.ts
  common/v2/services/AssetOption/types.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
Labels: type: GAU

#2532 Remove 'Confirm Address' View
  common/v2/features/AddAccount/AddAccount.tsx
  common/v2/features/DevTools/DevTools.tsx
  common/v2/providers/AccountProvider/AccountProvider.tsx
  common/v2/services/Account/types.ts
  common/v2/services/LocalCache/constants.ts
Labels: type: GAU

#2496 Feature/screen lock
  common/Root.tsx
  common/assets/images/icn-create-pw.svg
  common/assets/images/icn-forgot-password.svg
  common/assets/images/icn-unlock-wallet.svg
  common/translations/lang/en.json
  common/v2/components/ExtendedContentPanel.tsx
  common/v2/components/index.ts
  common/v2/features/ScreenLock/ScreenLockForgotPassword/ScreenLockForgotPassword.tsx
  common/v2/features/ScreenLock/ScreenLockForgotPassword/index.ts
  common/v2/features/ScreenLock/ScreenLockLocked/ScreenLockLocked.tsx
  common/v2/features/ScreenLock/ScreenLockLocked/index.ts
  common/v2/features/ScreenLock/ScreenLockLocking/ScreenLockLocking.tsx
  common/v2/features/ScreenLock/ScreenLockLocking/index.ts
  common/v2/features/ScreenLock/ScreenLockNew/ScreenLockNew.tsx
  common/v2/features/ScreenLock/ScreenLockNew/index.ts
  common/v2/features/ScreenLock/components/InputField.tsx
  common/v2/features/ScreenLock/index.ts
  common/v2/features/ScreenLock/routes.ts
  common/v2/features/constants.ts
  common/v2/features/index.ts
  common/v2/features/registry.json
  common/v2/providers/LockScreenProvider/LockScreenProvider.tsx
  common/v2/providers/LockScreenProvider/index.ts
  common/v2/providers/index.ts
  common/v2/services/Analytics/constants.ts
  common/v2/services/LocalCache/LocalCache.ts
  common/v2/services/LocalCache/constants.ts
  common/v2/services/ScreenLockSettings/ScreenLockSettings.ts
  common/v2/services/ScreenLockSettings/index.ts
  common/v2/services/ScreenLockSettings/types.ts
  common/v2/services/types.ts
  package.json
  yarn.lock
Labels: status: approved by qa, status: ready to merge, type: GAU
